root: true
extends:
  - standard
  - airbnb-base
env:
  es6: true
  node: true
rules:
  no-useless-escape: off
  no-param-reassign: off
  prettier/prettier: off
  prefer-rest-params: off
  no-underscore-dangle: off
  no-use-before-define: off
  unicorn/filename-case: off
  class-methods-use-this: off
  import/no-default-export: off
  curly:
    - error
  comma-dangle:
    - error
    - always-multiline
  id-length:
    - error
    -
      min: 2
      exceptions:
        - i
        - x
        - y
        - e
  id-match:
    - error
    - "^(([A-Za-z0-9]+){2,})|([A-Z][A-Z_0-9]+)$"
    -
      properties: false
      onlyDeclarations: true
  indent:
    - error
    - 2
    -
      SwitchCase: 1
  quotes:
    - error
    - single
  semi:
    - error
    - always
  space-before-function-paren:
    - error
    - always
